### ISSUE TITLE
[기획] 게임 컨셉

### ISSUE THREAD

**Issue by seong0929** [seong0929/Platypus#10]
## 게임 배경
`마공학이 발전한 Fluffonia 행성.
Fluffonia 행성은 자원 부족으로 인한 기아와 전쟁에 고통받고 있었다.
모두가 전쟁에 지쳐있던 그때, 획기적인 발명품이 나온다.
바로 ‘Platypus(게임이름)’. 완벽한 전쟁 시뮬레이션 게임.
부족들은 불필요한 폭력없이 ‘Platypus(게임이름)’으로 승부를 결정하기로 협의를 본다.'

**Comment by KimDa99** [comment]
아케인 펑크 + 기업 국가 + 중세

**Comment by KimDa99** [comment]
플레이어: 나라의 소대장 

플레이어가 하는 일:
- 파일럿 들을 뽑아, 훈련을 시키고, 게임 전략을 짠다.
- 들어가는 전투 병력들이 유동적으로 변함

**Comment by seong0929** [comment]
소환수를 다루는 세상
이 세상에서는 소환수로 전투를 치르는 스포츠가 인기이다.

이 세상사람들은 소환수를 데리고 1대1, 2대2,..., 점령전, 데스메치 등 다양한 방식으로 스포츠를 즐기고 있다.
큰 대회에서는 이를 더욱 즐겁게 할 수 있게 상대방의 소환수를 금지시키는 방식을 도입하여 좀 더 전문적인 스포츠로 발전하였다.

나 "{플레이어 이름}"은 세계 최고 소환수가 되고자 한 나는 현재 소환수를 다룰 수 있는 나이가 되어 내 꿈을 실현시키고자 한다.

+ 한 사람 여러 종류를 소환할 수 있지만, 한 소환수만 소환할 수 있어 다대다를 할려면 팀을 짜야한다.

**Comment by KimDa99** [comment]
소환수 격투를 하는 스포츠 'Platypus (게임이름)'

팀의 감독으로서 뛰어난 소환사들을 고르고 훈련시켜 최고의 팀으로 만들자!

**Comment by KimDa99** [comment]
소환의 별의 축복을 받고 태어난 fluffonia행성

**Comment by seong0929** [comment]
[마법의 돌  운영 시스템 추가](https://github.com/seong0929/Platypus/issues/18)

**Comment by seong0929** [comment]
“ 소환의 별의 축복을 받고 태어난 fluffonia행성.
'마법의 돌'을 바치면 소환수는 소환사의 부름에 응한다.
팀으로 소환수들을 다뤄 전투하는 스포츠 'Platypus'
감독이 되어 성공적인 스포츠 팀을 만들자! ”
