### ISSUE TITLE
[기획] 씬 예상도

### ISSUE THREAD

**Issue by KimDa99** [seong0929/Platypus#11]
# 게임 인트로
- 스킵 가능

“마공학이 발전한 Fluffonia 행성.
Fluffonia 행성은 자원 부족으로 인한 기아와 전쟁에 고통받고 있었다.
모두가 전쟁에 지쳐있던 그때, 획기적인 발명품이 나온다.
바로 ‘Platypus(게임이름)’. 완벽한 전쟁 시뮬레이션 게임.
부족들은 불필요한 폭력없이 ‘Platypus(게임이름)’으로 승부를 결정하기로 협의를 본다.”

ex)
![image](https://user-images.githubusercontent.com/91198933/224474363-b4e62491-5138-46fa-8ec2-7eb887a19be8.png)
![image](https://user-images.githubusercontent.com/91198933/224474440-bbf74f5c-efd5-4094-acd2-ffed9567d224.png)

**Comment by KimDa99** [comment]
# 게임 메인 화면
## 새로 시작하기
## 이어하기
## 옵션
## 종료
![image](https://user-images.githubusercontent.com/91198933/224474493-66044717-b054-4059-8417-0e2e7489ca5c.png)

**Comment by KimDa99** [comment]
'팀파이트 매니저'에서 그대로 따왔을때의 인게임 화면
![image](https://user-images.githubusercontent.com/91198933/224474579-878787d9-5cc9-4707-b9f5-fefad3c5e48a.png)

[기본 대기 화면]
부대 관리
- 소대원 정보
- 훈련
- 파일럿 영입

운영
- 소식함
- 장비
- 정부 미션
- 역사

전투
- 유닛 통계
- 소대 통계
- 순위표
- 일정

게임
- 유닛 정보 (캐릭터 능력치, 설명 정보)
- 조합 테스트

시스템
- 환경 설정
- 저장
- 타이틀로

일정 진행:
- 영입 기간
- 소대 간, 연습경기
- 경기
- 휴가

**Comment by seong0929** [comment]
* [화면 구성 예상도](https://docs.google.com/presentation/d/1iN1nLPNGC6dPj8Pu5-e1P0AR5Q1sTDujeAUZr7R-VEo/edit#slide=id.g2133d5e4f5a_0_62)

**Comment by KimDa99** [comment]
# 설정

**Comment by KimDa99** [comment]
# 게임 운영 화면
#12
