### ISSUE TITLE
[기획] 캐릭터 구상

### ISSUE THREAD

**Issue by KimDa99** [seong0929/Platypus#2]
# 캐릭터
### 오리너구리
* 근거리 딜러
![Platypus_IDLE100](https://user-images.githubusercontent.com/91198933/226520036-992d463f-e7a8-46cc-aa5b-397a05ac41b0.gif)

* 펜싱칼을 주무기로 사용
![Platypus_Attack100](https://user-images.githubusercontent.com/91198933/226519777-02338755-f075-4973-a860-25327654f567.gif)

* 특징
   * 낮은 체력
   * 빠른 공속
   * 풋웍(Foot Work): 거리 벌리고 줄이는 스킬
![PlatypusBlurMove100](https://user-images.githubusercontent.com/91198933/226521831-93583cbe-4a43-4922-8eed-1e3fb7978d12.gif)

   * 플래시(Fleche): 강력한 일인궁 
![Platypus_ULT100](https://user-images.githubusercontent.com/91198933/226520707-83ca5b92-50ac-441c-ba72-34541027451a.gif)

### 항아리를 짊은 두꺼비
* 탱커 or 지원가
![ToadSketch](https://user-images.githubusercontent.com/91198933/226518688-17bbba36-8530-44c5-8164-c08e8844518e.png)

###  호랑이
* 원거리 딜러
![TigerSketch](https://user-images.githubusercontent.com/91198933/226518774-fd4c8fa9-9cb6-4dfc-956a-be33ce1944cf.png)

* 일반 공격: 떡을 던짐
* 궁: 너덜너덜한 밧줄로 끌어당기다 중간에 끊어짐

### 아기 공룡
* 탱커 or 지원가
![DinoSketch](https://user-images.githubusercontent.com/91198933/226519104-b05a6714-c6e8-4845-a319-7c64fe833e13.png)

* 아이디어: 알에 숨기, 색깔 바꿔가면서 스킬 쓰기

### 상엉양 (고등어)
![SharkiSketch](https://user-images.githubusercontent.com/91198933/226519271-682a101f-9f96-4972-b45c-fbfdda8d85aa.png)
 * 상어가 되고 싶은 고등어, 등에 붙어있는 지느러미 - 는 사실 인위적으로 붙인 것이다. 위급시에 떼어서 공격한다.
![SharkirxSketch](https://user-images.githubusercontent.com/91198933/226525128-c4434c88-21e9-4742-8ed0-6866210a92a2.png)

***
### 퉷스터
![image](https://github.com/seong0929/Platypus/assets/91198933/ace980e7-be0a-4c31-a60d-3140743a94a0)

* 원거리 캐릭터
* 볼에 빵빵하게 씨앗을 가지고 다니는 날다람쥐 캐릭터

* 일반공격: 볼에 들어가 있던 씨앗 뱉기
![image](https://github.com/seong0929/Platypus/assets/91198933/ef43f354-b142-46be-9381-11a94e5d5dc3)

* 스킬: 꼬리로 때리기
![image](https://github.com/seong0929/Platypus/assets/91198933/0561877c-3bee-42db-82c7-f668faa80ee0)

* 궁: 폭격, 공중으로 날아가 범위 폭격

### 제물 양(신부 염소)
![image](https://github.com/seong0929/Platypus/assets/91198933/cbfdabb2-c676-4584-8eb8-1c8e65e451d6)
* 마법사 / 힐러
* 일반 공격: 자기 피 깎으면 천사 소환
* 궁: 악마 소환
![image](https://github.com/seong0929/Platypus/assets/91198933/8ca772b5-4786-4b66-82c8-a64029710fe3)

### 향수 뿌리는 스컹크
* 힐러

### 자만심 넘치는 토끼
* 전사

***
### 싱글
* 싱글 모드는 현실 시간 일주일 기준으로 자동 패치

**Comment by seong0929** [comment]
1. 펜싱을 하는 오리너구리
- 공격
![공격](https://user-images.githubusercontent.com/50050003/225539218-f2d905a9-af70-4e92-9cf2-0247dc85ed89.gif)
- 제자리
![제자리](https://user-images.githubusercontent.com/50050003/225539234-30c72d97-2463-4ca1-83b5-2167cfc02817.gif)

**Comment by seong0929** [comment]
왼쪽을 바라보고 있어야 함

**Comment by seong0929** [comment]
[캐릭터 프로젝트 창](https://github.com/users/seong0929/projects/13/views/1)을 통해 관리 예정
