### ISSUE TITLE
[기획] 전투원 관련

### ISSUE THREAD

**Issue by seong0929** [seong0929/Platypus#7]
## 전투원 능력치
- 숙련도 높은 캐릭터
  - 숙련도가 높은 캐릭터 사용 시 추가 능력치 부여
- 성격
  - 게임 플레이 스타일이 바뀜(성격에 따라 메서드 일부 추가 및 변경)
     - ex) 겁쟁이: 체력이 적을 경우 뒤로 물러남, 성급함: 궁극기를 지시와 상관없이 바로 사용함, 소심함: 첫 출전 시 숙련도 10감소, 클러치 선수: 끝나기 30초 전부터 숙련도가 20상승함 
- 나이: 나이가 오를 수록 선수 능력치 랜덤 하향

## 전투언 획득 방법
- 트레이드
- 영입
- 인재 발굴

**Comment by KimDa99** [comment]
## 디자인

다음과 같은 디자인을 조합하여 여러 캐릭터를 생성할 것

### 머리
* 민머리
* 올린 머리
* 짧은 머리
* 아프로 머리
* 단발
* 장발

### 앞머리
* 풀 뱅
* 시스루

### 하의
* 긴 바지
* 반 바지

### 상의
* 반 팔
* 긴 팔

### 망토
* 있음
* 없음

### 얼굴
* 둥근 얼굴
* 날렵한 얼굴

### 눈
* . .
* -. .-
* - -
* ㅣ ㅣ

### 모자
* 없음
* 콘
* 마법사 모자
* 로브 모자

### 지팡이
* C
* <>
* /
* 기본

**Comment by seong0929** [comment]
선수 능력치는 ATK, DFS를 지니며, 이 능력치는 소환수에 영향을 미침
나이를 지우고, 선수의 레벨을 추가
선수의 레벨은 랜덤하게 초기화 되며, 선수의 능력치 등급 매기는 용도
