### ISSUE TITLE
[기획] 에셋 관련

### ISSUE THREAD

**Issue by seong0929** [seong0929/Platypus#8]
# 에셋 기본
- [에셋이 나오기 전 테스트용 픽셀 에셋](https://assetstore.unity.com/publishers/31468)
  - 한 캐릭터에 여럿 행동이 들어간 스프라이트
     - ![image](https://user-images.githubusercontent.com/50050003/223353046-1fa52d2f-17b3-4d2c-873d-4f9374bb7485.png)
  - 단일 스프라이트
     - ![image](https://user-images.githubusercontent.com/50050003/223353164-2fb2a912-14c2-4801-9ff3-ce1fd6fae9ec.png)

# 에셋 컨셉

# UI

# Map 아이디어
- 결투장
- 호수
- 용암
- 정글

**Comment by KimDa99** [comment]
# 오리너구리 에셋 테스트
![ThePlatypus](https://user-images.githubusercontent.com/91198933/225548095-5f1204ab-86f1-4618-83df-92ab0f2c885b.png)
![ThePlatypusT0](https://user-images.githubusercontent.com/91198933/225548105-a0eb93bc-6a9c-4941-9e95-fcfb519e3966.png)
![ThePlatypus](https://user-images.githubusercontent.com/91198933/225548117-d35e6412-bd99-489a-868a-f6145e099045.gif)

**Comment by KimDa99** [comment]
- 스프라이트 툴 익힘
- 게임에 쓸 수 있는 익스포트 익힘

**Comment by seong0929** [comment]
필요한 스프라이트
- 궁
- 스킬
- 공격
- 이동
- Idle
- 데스
- 피격

**Comment by seong0929** [comment]
피격 표시가 필요하다면 모션이 아니라 테두리의 색의 바꾼다던가, 데미지를 띄워주거나, 캐릭터가 깜빡거린다던가, 캐릭터의 색상이 약간 빨간색으로 변하는 식으로

**Comment by KimDa99** [comment]
#15
